info:
  contact: {}
paths:
  /helloworld:
    get:
      consumes:
      - application/json
      description: do hello-world
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: hello world example
      tags:
      - example
  /ws:
    get:
      consumes:
      - application/json
      description: do ws connection by topic
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: ws connection
      tags:
      - example
    post:
      consumes:
      - application/json
      description: do send ws message by topic
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ws send message example
      tags:
      - example
swagger: "2.0"
